### ISSUE TITLE
when build lineageos16 with your tree, i got this, how can i fix it.plz

### ISSUE THREAD

**Issue by Ni1994** [yurical/android_device_xiaomi_clover#1]
[571/950] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
system/sepolicy/Android.mk:89: warning: Be careful when using the SELINUX_IGNORE_NEVERALLOWS flag. It does not work in user builds and using it will not stop you from failing CTS.
[950/950] including vendor/xiaomi/clover/Android.mk ...
external/wpa_supplicant_8/hostapd/Android.mk: error: hostapd (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
external/wpa_supplicant_8/wpa_supplicant/Android.mk: error: wpa_supplicant (EXECUTABLES android-arm64) missing lib_driver_cmd_qcwcn (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm64) missing libwifi-hal-qcom (STATIC_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm64) missing libcld80211 (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm) missing libwifi-hal-qcom (STATIC_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
frameworks/opt/net/wifi/libwifi_hal/Android.mk: error: libwifi-hal (SHARED_LIBRARIES android-arm) missing libcld80211 (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/audio-caf/msm8998/hal/Android.mk: error: audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing libtinycompress_vendor (SHARED_LIBRARIES android-arm64) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/audio-caf/msm8998/hal/Android.mk: error: audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing libtinycompress_vendor (SHARED_LIBRARIES android-arm) 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:837: error: exiting from previous errors.
04:17:47 ckati failed with: exit status 1

**Comment by yurical** [comment]
Hello @Ni1994.

Unfortunately, I haven't even tried building lineage-16.0. You might have to fix error yourself.
Currently I'm working on the lineage-15.1 branch, and lineage-16.0 branch is for the testing purpose only. I just cherry-picked some commits related to clover for now.
In addition, I'll do some more rebase before Xiaomi release the kernel source so it will be difficult to track the changes. Have you tried building lineage-16.0 with @GuaiYiHu's great work?

**Comment by Ni1994** [comment]
@yurical  got it, thanks
